server:
  port: ${SERVER_PORT}

# CORS 설정 - 개발 환경
cors:
  allowed-origins: "*"  # 모든 origin 허용 (앱 개발 + 로컬 웹 테스트)

service:
  auth:
    url: ${AUTH_URL}
    port: ${AUTH_PORT}

  profile:
    url: ${PROFILE_URL}
    port: ${PROFILE_PORT}

  image:
    url: ${IMAGE_URL}
    port: ${IMAGE_PORT}

  article:
    url: ${ARTICLE_URL}
    port: ${ARTICLE_PORT}

  comment:
    url: ${COMMENT_URL}
    port: ${COMMENT_PORT}

  gaechu:
    url: ${GAECHU_URL}
    port: ${GAECHU_PORT}
  activity:
    url: ${ACTIVITY_URL}
    port: ${ACTIVITY_PORT}
  support:
    url: ${SUPPORT_URL}
    port: ${SUPPORT_PORT}


  place_info:
    url: ${PLACE_INFO_URL}
    port: ${PLACE_INFO_PORT}

  room_info:
    url: ${ROOM_INFO_URL}
    port: ${ROOM_INFO_PORT}

  lee_yong_gwan_lee:
    url: ${LEE_YONG_GWAN_LEE_URL}
    port: ${LEE_YONG_GWAN_LEE_PORT}

  ye_yak_hae_yo:
    url: ${YE_YAK_HAE_YO_URL}
    port: ${YE_YAK_HAE_YO_PORT}

  ye_yak_manage:
    url: ${YE_YAK_MANAGE_URL}
    port: ${YE_YAK_MANAGE_PORT}

  coupon:
    url: ${COUPON_URL}
    port: ${COUPON_PORT}


